services:
  ipxe:
    build:
      context: ./pihole
      dockerfile: Dockerfile
    image: fabrik/ipxe
    network_mode: host
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    container_name: ipxe
    environment:
      - TZ=Europe/Paris
      - WEBPASSWORD=fabrik
      - DHCP_ACTIVE=true
      - DHCP_START=192.168.1.100
      - DHCP_END=192.168.1.150
      - DHCP_ROUTER=192.168.1.254
    volumes:
      - ./pihole/20-pxeconfig.conf:/etc/dnsmasq.d/20-pxe.conf
      - ./export/:/srv/tftpboot/export
      - ./pihole/install.ipxe:/var/www/html/install.ipxe
      - ./pihole/serve_driver.php:/var/www/html/serve_driver.php

  samba:
    build:
      context: ./samba
      dockerfile: Dockerfile
    image: fabrik/samba
    ports:
      - 139:139
      - 445:445
    restart: unless-stopped
    volumes:
      - ./export:/srv/samba
